### PR TITLE
[refactor][style] Implement various improvements to Map page  + EventCard

### PR DESCRIPTION
**Pull request by Michael-Parekh**
- remove unnecessary components in Map page
- add dynamic details to EventCard

### CODE REVIEW

**Review by yhuang0701 — APPROVED** [review]
Awesome work

**Comment by szhuang21** [comment]
where are the images?

**Comment by szhuang21** [comment]
this is a lame PR

**Comment by Michael-Parekh** [comment]
ur not even on our team smh

**Pull request merged**
